In [33]:
import pandas as pd

In [187]:
df = pd.read_csv('OnlineArrestData1980-2018.csv')

In [188]:
df.head(20)

,YEAR,GENDER,RACE,AGE_GROUP,COUNTY,VIOLENT,PROPERTY,F_DRUGOFF,F_SEXOFF,F_ALLOTHER,F_TOTAL,M_TOTAL,S_TOTAL
0,1980,Male,Black,Under 18,Alameda County,505,1351,188,26,79,2149,2286,295
1,1980,Male,Black,Under 18,Butte County,3,5,0,0,0,8,7,0
2,1980,Male,Black,Under 18,Calaveras County,0,0,0,0,0,0,1,0
3,1980,Male,Black,Under 18,Contra Costa County,116,446,28,2,37,629,557,31
4,1980,Male,Black,Under 18,El Dorado County,0,1,0,1,0,2,6,0
5,1980,Male,Black,Under 18,Fresno County,123,307,4,4,22,460,355,58
6,1980,Male,Black,Under 18,Glenn County,0,0,0,0,0,0,1,0
7,1980,Male,Black,Under 18,Humboldt County,0,1,0,0,0,1,2,1
8,1980,Male,Black,Under 18,Imperial County,6,4,0,0,2,12,9,1
9,1980,Male,Black,Under 18,Inyo County,0,0,0,0,0,0,0,0
10,1980,Male,Black,Under 18,Kern County,57,177,14,4,4,256,301,27
11,1980,Male,Black,Under 18,Kings County,6,26,0,3,3,38,64,5
12,1980,Male,Black,Under 18,Lake County,0,0,0,0,0,0,2,0
13,1980,Male,Black,Under 18,Lassen County,0,1,0,0,0,1,2,0
14,1980,Male,Black,Under 18,Los Angeles County,4180,7672,862,85,716,13515,5696,618
15,1980,Male,Black,Under 18,Madera County,2,14,0,0,0,16,14,0
16,1980,Male,Black,Under 18,Marin County,10,19,2,0,2,33,65,8
17,1980,Male,Black,Under 18,Mariposa County,0,1,0,0,0,1,0,0
18,1980,Male,Black,Under 18,Mendocino County,1,3,0,0,0,4,4,0
19,1980,Male,Black,Under 18,Merced County,11,42,1,1,0,55,102,32

In [189]:
alameda = df.loc[df['COUNTY']=='Alameda County']

In [190]:
alameda = al.loc[al['YEAR'] == 2018]

In [191]:
alameda

,YEAR,GENDER,RACE,AGE_GROUP,COUNTY,VIOLENT,PROPERTY,F_DRUGOFF,F_SEXOFF,F_ALLOTHER,F_TOTAL,M_TOTAL,S_TOTAL
92387,2018,Male,Black,Under 18,Alameda County,218,132,3,3,51,407,152,18
92435,2018,Male,Black,18 to 19,Alameda County,95,51,8,2,99,255,131,0
92485,2018,Male,Black,20 to 29,Alameda County,432,275,91,19,375,1192,1705,0
92542,2018,Male,Black,30 to 39,Alameda County,319,232,93,17,238,899,1764,0
92599,2018,Male,Black,40 to 69,Alameda County,387,323,168,30,246,1154,2642,0
92656,2018,Male,Black,70 and over,Alameda County,5,3,0,0,1,9,33,0
92687,2018,Male,Hispanic,Under 18,Alameda County,86,58,5,4,33,186,120,12
92739,2018,Male,Hispanic,18 to 19,Alameda County,69,44,13,2,54,182,240,0
92796,2018,Male,Hispanic,20 to 29,Alameda County,310,210,100,10,247,877,2504,0
92854,2018,Male,Hispanic,30 to 39,Alameda County,192,164,68,14,157,595,1950,0
92911,2018,Male,Hispanic,40 to 69,Alameda County,171,121,58,21,97,468,1708,0
92968,2018,Male,Hispanic,70 and over,Alameda County,0,0,1,0,1,2,4,0
93015,2018,Male,Other,Under 18,Alameda County,19,11,3,1,6,40,38,4
93068,2018,Male,Other,18 to 19,Alameda County,18,8,2,0,6,34,86,0
93122,2018,Male,Other,20 to 29,Alameda County,113,62,30,8,58,271,757,0
93180,2018,Male,Other,30 to 39,Alameda County,92,73,31,1,55,252,752,0
93238,2018,Male,Other,40 to 69,Alameda County,119,50,27,2,38,236,773,0
93296,2018,Male,Other,70 and over,Alameda County,4,0,0,2,0,6,16,0
93343,2018,Male,White,Under 18,Alameda County,28,17,2,5,5,57,67,3
93399,2018,Male,White,18 to 19,Alameda County,10,15,1,0,12,38,94,0
93455,2018,Male,White,20 to 29,Alameda County,135,132,50,1,120,438,1546,0
93513,2018,Male,White,30 to 39,Alameda County,160,136,69,7,123,495,1628,0
93571,2018,Male,White,40 to 69,Alameda County,189,160,97,21,179,646,2437,0
93629,2018,Male,White,70 and over,Alameda County,10,3,1,0,1,15,57,0
93685,2018,Female,Black,Under 18,Alameda County,50,37,0,1,5,93,126,21
93729,2018,Female,Black,18 to 19,Alameda County,27,26,1,0,8,62,129,0
93768,2018,Female,Black,20 to 29,Alameda County,161,135,10,0,75,381,1015,0
93821,2018,Female,Black,30 to 39,Alameda County,109,90,14,0,55,268,612,0
93874,2018,Female,Black,40 to 69,Alameda County,136,76,9,2,53,276,685,0
93925,2018,Female,Black,70 and over,Alameda County,4,1,0,0,0,5,11,0
93947,2018,Female,Hispanic,Under 18,Alameda County,17,10,1,0,1,29,38,21
93999,2018,Female,Hispanic,18 to 19,Alameda County,17,10,0,0,5,32,82,0
94048,2018,Female,Hispanic,20 to 29,Alameda County,67,45,9,0,33,154,594,0
94105,2018,Female,Hispanic,30 to 39,Alameda County,56,70,9,0,30,165,442,0
94161,2018,Female,Hispanic,40 to 69,Alameda County,26,19,3,0,13,61,320,0
94217,2018,Female,Hispanic,70 and over,Alameda County,0,0,0,0,0,0,4,0
94248,2018,Female,Other,Under 18,Alameda County,5,0,0,0,2,7,20,2
94296,2018,Female,Other,18 to 19,Alameda County,5,8,0,0,0,13,22,0
94341,2018,Female,Other,20 to 29,Alameda County,30,18,3,0,17,68,251,0
94399,2018,Female,Other,30 to 39,Alameda County,43,19,3,0,7,72,219,0
94457,2018,Female,Other,40 to 69,Alameda County,29,12,12,0,4,57,213,0
94513,2018,Female,Other,70 and over,Alameda County,1,0,0,0,0,1,5,0
94539,2018,Female,White,Under 18,Alameda County,6,4,0,0,1,11,17,1
94594,2018,Female,White,18 to 19,Alameda County,9,2,0,0,2,13,41,0
94648,2018,Female,White,20 to 29,Alameda County,49,67,26,0,41,183,714,0
94706,2018,Female,White,30 to 39,Alameda County,40,62,24,0,37,163,674,0
94764,2018,Female,White,40 to 69,Alameda County,62,59,17,0,28,166,827,0
94822,2018,Female,White,70 and over,Alameda County,2,1,0,0,0,3,40,0

In [192]:
la = df.loc[df['COUNTY']=='Los Angeles County']

In [193]:
la = la.loc[la['YEAR']==2018]

In [194]:
la

,YEAR,GENDER,RACE,AGE_GROUP,COUNTY,VIOLENT,PROPERTY,F_DRUGOFF,F_SEXOFF,F_ALLOTHER,F_TOTAL,M_TOTAL,S_TOTAL
92401,2018,Male,Black,Under 18,Los Angeles County,571,365,4,23,158,1121,554,23
92450,2018,Male,Black,18 to 19,Los Angeles County,426,310,27,5,216,984,555,0
92503,2018,Male,Black,20 to 29,Los Angeles County,2184,1318,283,54,1534,5373,7277,0
92560,2018,Male,Black,30 to 39,Los Angeles County,1418,744,300,45,1066,3573,6305,0
92617,2018,Male,Black,40 to 69,Los Angeles County,1832,641,579,83,904,4039,9879,0
92662,2018,Male,Black,70 and over,Los Angeles County,52,3,7,2,9,73,197,0
92704,2018,Male,Hispanic,Under 18,Los Angeles County,799,396,59,61,510,1825,1683,181
92757,2018,Male,Hispanic,18 to 19,Los Angeles County,714,469,119,29,603,1934,2482,0
92814,2018,Male,Hispanic,20 to 29,Los Angeles County,4625,3516,987,125,3697,12950,28409,0
92872,2018,Male,Hispanic,30 to 39,Los Angeles County,3190,2248,916,148,2344,8846,21014,0
92928,2018,Male,Hispanic,40 to 69,Los Angeles County,2344,1267,740,217,1593,6161,19178,0
92982,2018,Male,Hispanic,70 and over,Los Angeles County,40,0,11,14,8,73,210,0
93032,2018,Male,Other,Under 18,Los Angeles County,50,13,1,6,12,82,119,16
93086,2018,Male,Other,18 to 19,Los Angeles County,28,15,6,2,19,70,201,0
93140,2018,Male,Other,20 to 29,Los Angeles County,378,194,90,10,202,874,2084,0
93198,2018,Male,Other,30 to 39,Los Angeles County,359,251,87,10,185,892,2006,0
93256,2018,Male,Other,40 to 69,Los Angeles County,420,183,76,28,180,887,2340,0
93309,2018,Male,Other,70 and over,Los Angeles County,30,0,0,4,7,41,89,0
93361,2018,Male,White,Under 18,Los Angeles County,108,54,2,14,37,215,279,29
93416,2018,Male,White,18 to 19,Los Angeles County,75,60,17,3,47,202,464,0
93473,2018,Male,White,20 to 29,Los Angeles County,788,664,254,23,606,2335,6847,0
93531,2018,Male,White,30 to 39,Los Angeles County,881,766,280,16,717,2660,7687,0
93589,2018,Male,White,40 to 69,Los Angeles County,1263,778,463,76,885,3465,12879,0
93646,2018,Male,White,70 and over,Los Angeles County,44,6,1,5,14,70,310,0
93695,2018,Female,Black,Under 18,Los Angeles County,158,71,0,3,30,262,353,9
93740,2018,Female,Black,18 to 19,Los Angeles County,132,77,6,1,43,259,516,0
93785,2018,Female,Black,20 to 29,Los Angeles County,788,456,50,3,288,1585,3621,0
93837,2018,Female,Black,30 to 39,Los Angeles County,470,253,48,0,190,961,2086,0
93890,2018,Female,Black,40 to 69,Los Angeles County,471,210,90,1,168,940,2444,0
93929,2018,Female,Black,70 and over,Los Angeles County,3,1,0,0,0,4,49,0
93964,2018,Female,Hispanic,Under 18,Los Angeles County,180,111,15,2,62,370,697,75
94014,2018,Female,Hispanic,18 to 19,Los Angeles County,174,106,22,0,45,347,814,0
94066,2018,Female,Hispanic,20 to 29,Los Angeles County,1267,1176,212,3,580,3238,7085,0
94122,2018,Female,Hispanic,30 to 39,Los Angeles County,756,682,181,5,372,1996,4975,0
94178,2018,Female,Hispanic,40 to 69,Los Angeles County,484,302,140,1,241,1168,4065,0
94225,2018,Female,Hispanic,70 and over,Los Angeles County,4,0,0,0,1,5,25,0
94263,2018,Female,Other,Under 18,Los Angeles County,5,8,0,0,2,15,51,5
94309,2018,Female,Other,18 to 19,Los Angeles County,8,10,0,0,0,18,93,0
94359,2018,Female,Other,20 to 29,Los Angeles County,127,79,20,0,42,268,721,0
94417,2018,Female,Other,30 to 39,Los Angeles County,126,79,12,1,37,255,621,0
94474,2018,Female,Other,40 to 69,Los Angeles County,122,53,15,2,27,219,759,0
94518,2018,Female,Other,70 and over,Los Angeles County,8,1,0,0,1,10,26,0
94556,2018,Female,White,Under 18,Los Angeles County,19,16,3,1,14,53,107,9
94611,2018,Female,White,18 to 19,Los Angeles County,15,28,8,1,16,68,242,0
94666,2018,Female,White,20 to 29,Los Angeles County,270,330,88,0,177,865,2888,0
94724,2018,Female,White,30 to 39,Los Angeles County,276,357,91,2,175,901,3004,0
94782,2018,Female,White,40 to 69,Los Angeles County,375,232,100,0,190,897,4038,0
94837,2018,Female,White,70 and over,Los Angeles County,8,2,2,0,2,14,61,0

In [104]:
la

,YEAR,GENDER,RACE,AGE_GROUP,COUNTY,VIOLENT,PROPERTY,F_DRUGOFF,F_SEXOFF,F_ALLOTHER,F_TOTAL,M_TOTAL,S_TOTAL
92503,2018,Male,Black,20 to 29,Los Angeles County,2184,1318,283,54,1534,5373,7277,0
92560,2018,Male,Black,30 to 39,Los Angeles County,1418,744,300,45,1066,3573,6305,0
92617,2018,Male,Black,40 to 69,Los Angeles County,1832,641,579,83,904,4039,9879,0
92814,2018,Male,Hispanic,20 to 29,Los Angeles County,4625,3516,987,125,3697,12950,28409,0
92872,2018,Male,Hispanic,30 to 39,Los Angeles County,3190,2248,916,148,2344,8846,21014,0
92928,2018,Male,Hispanic,40 to 69,Los Angeles County,2344,1267,740,217,1593,6161,19178,0
93140,2018,Male,Other,20 to 29,Los Angeles County,378,194,90,10,202,874,2084,0
93198,2018,Male,Other,30 to 39,Los Angeles County,359,251,87,10,185,892,2006,0
93256,2018,Male,Other,40 to 69,Los Angeles County,420,183,76,28,180,887,2340,0
93473,2018,Male,White,20 to 29,Los Angeles County,788,664,254,23,606,2335,6847,0
93531,2018,Male,White,30 to 39,Los Angeles County,881,766,280,16,717,2660,7687,0
93589,2018,Male,White,40 to 69,Los Angeles County,1263,778,463,76,885,3465,12879,0
93785,2018,Female,Black,20 to 29,Los Angeles County,788,456,50,3,288,1585,3621,0
93837,2018,Female,Black,30 to 39,Los Angeles County,470,253,48,0,190,961,2086,0
93890,2018,Female,Black,40 to 69,Los Angeles County,471,210,90,1,168,940,2444,0
94066,2018,Female,Hispanic,20 to 29,Los Angeles County,1267,1176,212,3,580,3238,7085,0
94122,2018,Female,Hispanic,30 to 39,Los Angeles County,756,682,181,5,372,1996,4975,0
94178,2018,Female,Hispanic,40 to 69,Los Angeles County,484,302,140,1,241,1168,4065,0
94359,2018,Female,Other,20 to 29,Los Angeles County,127,79,20,0,42,268,721,0
94417,2018,Female,Other,30 to 39,Los Angeles County,126,79,12,1,37,255,621,0
94474,2018,Female,Other,40 to 69,Los Angeles County,122,53,15,2,27,219,759,0
94666,2018,Female,White,20 to 29,Los Angeles County,270,330,88,0,177,865,2888,0
94724,2018,Female,White,30 to 39,Los Angeles County,276,357,91,2,175,901,3004,0
94782,2018,Female,White,40 to 69,Los Angeles County,375,232,100,0,190,897,4038,0

In [195]:
#I needed to add all the crime together and di not need the year to add to my total. I know i'm in the year 2018 
# as I sorted it above.
crime_total_males = la.drop(columns = ['YEAR', 'VIOLENT', 'PROPERTY', 'F_DRUGOFF', 'F_SEXOFF', 'F_ALLOTHER'])

In [197]:
crime_total_males[crime_total_males.GENDER != 'Female']

,GENDER,RACE,AGE_GROUP,COUNTY,F_TOTAL,M_TOTAL,S_TOTAL
92401,Male,Black,Under 18,Los Angeles County,1121,554,23
92450,Male,Black,18 to 19,Los Angeles County,984,555,0
92503,Male,Black,20 to 29,Los Angeles County,5373,7277,0
92560,Male,Black,30 to 39,Los Angeles County,3573,6305,0
92617,Male,Black,40 to 69,Los Angeles County,4039,9879,0
92662,Male,Black,70 and over,Los Angeles County,73,197,0
92704,Male,Hispanic,Under 18,Los Angeles County,1825,1683,181
92757,Male,Hispanic,18 to 19,Los Angeles County,1934,2482,0
92814,Male,Hispanic,20 to 29,Los Angeles County,12950,28409,0
92872,Male,Hispanic,30 to 39,Los Angeles County,8846,21014,0
92928,Male,Hispanic,40 to 69,Los Angeles County,6161,19178,0
92982,Male,Hispanic,70 and over,Los Angeles County,73,210,0
93032,Male,Other,Under 18,Los Angeles County,82,119,16
93086,Male,Other,18 to 19,Los Angeles County,70,201,0
93140,Male,Other,20 to 29,Los Angeles County,874,2084,0
93198,Male,Other,30 to 39,Los Angeles County,892,2006,0
93256,Male,Other,40 to 69,Los Angeles County,887,2340,0
93309,Male,Other,70 and over,Los Angeles County,41,89,0
93361,Male,White,Under 18,Los Angeles County,215,279,29
93416,Male,White,18 to 19,Los Angeles County,202,464,0
93473,Male,White,20 to 29,Los Angeles County,2335,6847,0
93531,Male,White,30 to 39,Los Angeles County,2660,7687,0
93589,Male,White,40 to 69,Los Angeles County,3465,12879,0
93646,Male,White,70 and over,Los Angeles County,70,310,0

In [198]:
crime_total_males.drop(columns = 'AGE_GROUP', inplace=True)

In [200]:
crime_total_males

       GENDER      RACE              COUNTY  F_TOTAL  M_TOTAL  S_TOTAL
92401    Male     Black  Los Angeles County     1121      554       23
92450    Male     Black  Los Angeles County      984      555        0
92503    Male     Black  Los Angeles County     5373     7277        0
92560    Male     Black  Los Angeles County     3573     6305        0
92617    Male     Black  Los Angeles County     4039     9879        0
92662    Male     Black  Los Angeles County       73      197        0
92704    Male  Hispanic  Los Angeles County     1825     1683      181
92757    Male  Hispanic  Los Angeles County     1934     2482        0
92814    Male  Hispanic  Los Angeles County    12950    28409        0
92872    Male  Hispanic  Los Angeles County     8846    21014        0
92928    Male  Hispanic  Los Angeles County     6161    19178        0
92982    Male  Hispanic  Los Angeles County       73      210        0
93032    Male     Other  Los Angeles County       82      119       16
93086    Male     Other  Los Angeles County       70      201        0
93140    Male     Other  Los Angeles County      874     2084        0
93198    Male     Other  Los Angeles County      892     2006        0
93256    Male     Other  Los Angeles County      887     2340        0
93309    Male     Other  Los Angeles County       41       89        0
93361    Male     White  Los Angeles County      215      279       29
93416    Male     White  Los Angeles County      202      464        0
93473    Male     White  Los Angeles County     2335     6847        0
93531    Male     White  Los Angeles County     2660     7687        0
93589    Male     White  Los Angeles County     3465    12879        0
93646    Male     White  Los Angeles County       70      310        0
93695  Female     Black  Los Angeles County      262      353        9
93740  Female     Black  Los Angeles County      259      516        0
93785  Female     Black  Los Angeles County     1585     3621        0
93837  Female     Black  Los Angeles County      961     2086        0
93890  Female     Black  Los Angeles County      940     2444        0
93929  Female     Black  Los Angeles County        4       49        0
93964  Female  Hispanic  Los Angeles County      370      697       75
94014  Female  Hispanic  Los Angeles County      347      814        0
94066  Female  Hispanic  Los Angeles County     3238     7085        0
94122  Female  Hispanic  Los Angeles County     1996     4975        0
94178  Female  Hispanic  Los Angeles County     1168     4065        0
94225  Female  Hispanic  Los Angeles County        5       25        0
94263  Female     Other  Los Angeles County       15       51        5
94309  Female     Other  Los Angeles County       18       93        0
94359  Female     Other  Los Angeles County      268      721        0
94417  Female     Other  Los Angeles County      255      621        0
94474  Female     Other  Los Angeles County      219      759        0
94518  Female     Other  Los Angeles County       10       26        0
94556  Female     White  Los Angeles County       53      107        9
94611  Female     White  Los Angeles County       68      242        0
94666  Female     White  Los Angeles County      865     2888        0
94724  Female     White  Los Angeles County      901     3004        0
94782  Female     White  Los Angeles County      897     4038        0
94837  Female     White  Los Angeles County       14       61        0

In [201]:
ctm = crime_total_males.sum(axis=1)

In [210]:
ctm

92401     1698
92450     1539
92503    12650
92560     9878
92617    13918
92662      270
92704     3689
92757     4416
92814    41359
92872    29860
92928    25339
92982      283
93032      217
93086      271
93140     2958
93198     2898
93256     3227
93309      130
93361      523
93416      666
93473     9182
93531    10347
93589    16344
93646      380
93695      624
93740      775
93785     5206
93837     3047
93890     3384
93929       53
93964     1142
94014     1161
94066    10323
94122     6971
94178     5233
94225       30
94263       71
94309      111
94359      989
94417      876
94474      978
94518       36
94556      169
94611      310
94666     3753
94724     3905
94782     4935
94837       75
dtype: int64

In [202]:
#ctm is crime total for males. ctm is a pandas series
ctm.sum()

246199

In [203]:
crime_total_females = crime_total_males[crime_total_males.GENDER != 'Male']

In [204]:
crime_total_females

       GENDER      RACE              COUNTY  F_TOTAL  M_TOTAL  S_TOTAL
93695  Female     Black  Los Angeles County      262      353        9
93740  Female     Black  Los Angeles County      259      516        0
93785  Female     Black  Los Angeles County     1585     3621        0
93837  Female     Black  Los Angeles County      961     2086        0
93890  Female     Black  Los Angeles County      940     2444        0
93929  Female     Black  Los Angeles County        4       49        0
93964  Female  Hispanic  Los Angeles County      370      697       75
94014  Female  Hispanic  Los Angeles County      347      814        0
94066  Female  Hispanic  Los Angeles County     3238     7085        0
94122  Female  Hispanic  Los Angeles County     1996     4975        0
94178  Female  Hispanic  Los Angeles County     1168     4065        0
94225  Female  Hispanic  Los Angeles County        5       25        0
94263  Female     Other  Los Angeles County       15       51        5
94309  Female     Other  Los Angeles County       18       93        0
94359  Female     Other  Los Angeles County      268      721        0
94417  Female     Other  Los Angeles County      255      621        0
94474  Female     Other  Los Angeles County      219      759        0
94518  Female     Other  Los Angeles County       10       26        0
94556  Female     White  Los Angeles County       53      107        9
94611  Female     White  Los Angeles County       68      242        0
94666  Female     White  Los Angeles County      865     2888        0
94724  Female     White  Los Angeles County      901     3004        0
94782  Female     White  Los Angeles County      897     4038        0
94837  Female     White  Los Angeles County       14       61        0

In [205]:
ctf = crime_total_females.sum(axis=1)

In [206]:
ctf.sum()

54157

In [212]:
LA_arrest_toal = ctf.sum() + ctm.sum()

In [208]:
LA_arrest_toal

300356

In [161]:
10**7

10000000

In [213]:
LA_arrest_toal / 10105518

0.02972197961549324